/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.aws_project_region,
    "aws_cognito_identity_pool_id": process.env.aws_cognito_identity_pool_id,
    "aws_cognito_region": process.env.aws_cognito_region ,
    "aws_user_pools_id": process.env.aws_user_pools_id,
    "aws_user_pools_web_client_id": process.env.aws_user_pools_web_client_id ,
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": process.env.passwordPolicyMinLength ,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": process.env.aws_appsync_graphqlEndpoint,
    "aws_appsync_region": process.env.aws_appsync_region ,
    "aws_appsync_authenticationType": process.env.aws_appsync_authenticationType
};


export default awsmobile;
